version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: dynamo-localstack
    ports:
      - "4566:4566"  # LocalStack port
      - "4510-4559:4510-4559"  # External service port range
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_RUNTIME_EXECUTOR=docker
      - PERSISTENCE=1
      - PERSISTENCE_SKIP_INIT_DOWNLOAD=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack-network

  # Optional: DynamoDB Admin UI for easier management
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamo-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - localstack
    networks:
      - localstack-network

networks:
  localstack-network:
    driver: bridge 
